using System.Linq;
using Content.Client._Orion.Skills.Ui;
using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Skills;
using Content.Shared._Orion.Skills.Prototypes;
using Content.Shared._Orion.Skills.Ui;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Orion.Administration.UI;

//
// License-Identifier: GPL-3.0-or-later
//

[GenerateTypedNameReferences]
public sealed partial class SkillsAdminWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly SharedSkillsSystem _skillsSystem;

    public event Action<ProtoId<SkillPrototype>, int>? OnSkillChanged;
    public event Action<int>? OnPointsChanged;
    public event Action? OnResetAll;

    private Dictionary<ProtoId<SkillPrototype>, int> _currentSkills = new();
    private int _bonusPoints;
    private int _spentPoints;

    public SkillsAdminWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _skillsSystem = _entMan.System<SharedSkillsSystem>();

        CloseButton.OnPressed += _ => Close();
        ApplyPointsButton.OnPressed += OnApplyPoints;
        ResetButton.OnPressed += _ => OnResetAll?.Invoke();
    }

    public void UpdateState(SkillsAdminEuiState state)
    {
        TargetNameLabel.Text = state.EntityName;
        JobLabel.Text = state.CurrentJob;

        _currentSkills = state.CurrentSkills
            .ToDictionary(
                k => new ProtoId<SkillPrototype>(k.Key),
                k => k.Value);
        _bonusPoints = state.BonusPoints;
        _spentPoints = state.SpentPoints;

        UpdatePointsDisplay();
        PopulateSkills();
    }

    private void UpdatePointsDisplay()
    {
        BonusPointsEdit.Text = _bonusPoints.ToString();
        SpentPointsLabel.Text = _spentPoints.ToString();
    }

    private void PopulateSkills()
    {
        SkillsContainer.RemoveAllChildren();

        foreach (var skillProto in _entMan.System<SharedSkillsSystem>().GetAllSkillPrototypes())
        {
            var costs = _skillsSystem.GetSkillCost(skillProto);
            var color = _skillsSystem.GetSkillColor(skillProto);

            var currentLevel = _currentSkills.GetValueOrDefault(skillProto, 1);

            var skillSelector = new SkillSelector(skillProto, currentLevel, costs, color)
            {
                Margin = new Thickness(0, 5),
                HorizontalExpand = true,
            };

            skillSelector.IsLocked = false;
            skillSelector.UpdateAvailability(int.MaxValue, _skillsSystem);

            skillSelector.OnSkillLevelChanged += newLevel =>
            {
                _currentSkills[skillProto] = newLevel;
                OnSkillChanged?.Invoke(skillProto, newLevel);
            };

            SkillsContainer.AddChild(skillSelector);
        }
    }

    private void OnApplyPoints(BaseButton.ButtonEventArgs args)
    {
        if (int.TryParse(BonusPointsEdit.Text, out var newBonus))
        {
            OnPointsChanged?.Invoke(newBonus);
        }
    }
}
