using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Skills;
using Content.Shared._Orion.Skills.Prototypes;
using Content.Shared._Orion.Skills.Ui;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Orion.Skills.Ui;

//
// License-Identifier: GPL-3.0-or-later
//

[GenerateTypedNameReferences]
public sealed partial class SkillsForcedWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly SharedSkillsSystem _skillsSystem;

    public event Action<string, ProtoId<SkillPrototype>, int>? OnSkillChanged;

    private string _jobId = string.Empty;
    private Dictionary<ProtoId<SkillPrototype>, int> _currentSkills = new();
    private Dictionary<ProtoId<SkillPrototype>, int> _defaultSkills = new();
    private int _totalPoints;
    private int _spentPoints;

    public SkillsForcedWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _skillsSystem = _entMan.System<SharedSkillsSystem>();
    }

    public void UpdateState(SkillsEuiState state)
    {
        _jobId = state.JobId;
        _currentSkills = new Dictionary<ProtoId<SkillPrototype>, int>(state.CurrentSkills);
        _defaultSkills = new Dictionary<ProtoId<SkillPrototype>, int>(state.DefaultSkills);
        _totalPoints = state.TotalPoints;
        _spentPoints = state.SpentPoints;

        UpdateWindow();
    }

    private void UpdateWindow()
    {
        SkillsContainer.RemoveAllChildren();

        var pointsLabel = new Label
        {
            Text = $"{_totalPoints - _spentPoints} / {_totalPoints}",
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 0, 0, 10),
        };
        SkillsContainer.AddChild(pointsLabel);

        var warningLabel = new Label
        {
            Text = Loc.GetString("skills-forced-warning"),
            StyleClasses = { "LabelSubText" },
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 0, 0, 20),
        };
        SkillsContainer.AddChild(warningLabel);

        var scrollContainer = new ScrollContainer
        {
            VerticalExpand = true,
        };
        var skillsList = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        scrollContainer.AddChild(skillsList);

        PopulateSkillsList(skillsList);
        SkillsContainer.AddChild(scrollContainer);

        var bottomContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 20, 0, 0),
        };

        var confirmButton = new Button
        {
            Text = Loc.GetString("skills-confirm-button"),
            HorizontalAlignment = HAlignment.Center,
        };

        var warningContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
        };

        confirmButton.OnPressed += _ =>
        {
            if (_totalPoints - _spentPoints == 0)
            {
                Close();
            }
            else
            {
                warningContainer.RemoveAllChildren();
                var warning = new Label
                {
                    Text = Loc.GetString("skills-unspent-warning"),
                    FontColorOverride = Color.Yellow,
                    HorizontalAlignment = HAlignment.Center,
                };
                warningContainer.AddChild(warning);
            }
        };

        bottomContainer.AddChild(confirmButton);
        bottomContainer.AddChild(warningContainer);
        SkillsContainer.AddChild(bottomContainer);
    }

    private void PopulateSkillsList(BoxContainer skillsList)
    {
        var unspentPoints = _totalPoints - _spentPoints;

        foreach (var skillId in _skillsSystem.GetAllSkillPrototypes())
        {
            var costs = _skillsSystem.GetSkillCost(skillId);
            var color = _skillsSystem.GetSkillColor(skillId);

            var defaultLevel = _defaultSkills.GetValueOrDefault(skillId, 1);
            var currentLevel = _currentSkills.GetValueOrDefault(skillId, defaultLevel);

            var skillSelector = new SkillSelector(skillId, currentLevel, costs, color, defaultLevel)
            {
                Margin = new Thickness(0, 5)
            };

            skillSelector.IsLocked = defaultLevel == 4;
            skillSelector.UpdateAvailability(unspentPoints, _skillsSystem);

            skillSelector.OnSkillLevelChanged += (newLevel) =>
            {
                if (newLevel < defaultLevel)
                {
                    skillSelector.SetLevel(currentLevel);
                    return;
                }

                _currentSkills[skillId] = newLevel;
                OnSkillChanged?.Invoke(_jobId, skillId, newLevel);

                _spentPoints = CalculateTotalSpentPoints();
                UpdateWindow();
            };

            skillsList.AddChild(skillSelector);
        }
    }

    private int CalculateTotalSpentPoints()
    {
        var totalSpent = 0;

        foreach (var (skillId, level) in _currentSkills)
        {
            var costs = _skillsSystem.GetSkillCost(skillId);
            var defaultLevel = _defaultSkills.GetValueOrDefault(skillId, 1);

            for (var currentLevel = defaultLevel; currentLevel < level; currentLevel++)
            {
                if (currentLevel < costs.Length)
                    totalSpent += costs[currentLevel];
            }
        }

        return totalSpent;
    }
}
