using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Skills;
using Content.Shared._Orion.Skills.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Orion.Skills.Ui;

//
// License-Identifier: GPL-3.0-or-later
//

[GenerateTypedNameReferences]
public sealed partial class SkillsWindow : FancyWindow
{
    private readonly SharedSkillsSystem _skillsSystem;

    public event Action<string, ProtoId<SkillPrototype>, int>? OnSkillChanged;

    private readonly string _jobId;
    private readonly Dictionary<ProtoId<SkillPrototype>, int> _currentSkills;
    private readonly Dictionary<ProtoId<SkillPrototype>, int> _defaultSkills;
    private readonly bool _upgradeOnly;
    private readonly int _totalPoints;
    private int _spentPoints;

    private readonly Color _rowColor1 = Color.FromHex("#1B1B1E");
    private readonly Color _rowColor2 = Color.FromHex("#202025");
    private int _rowCount;

    public SkillsWindow(string jobId, Dictionary<ProtoId<SkillPrototype>, int> currentSkills, Dictionary<ProtoId<SkillPrototype>, int> defaultSkills, int totalPoints, bool upgradeOnly = false)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var entMan = IoCManager.Resolve<IEntityManager>();
        _skillsSystem = entMan.System<SharedSkillsSystem>();

        _jobId = jobId;
        _currentSkills = new(currentSkills);
        _defaultSkills = new(defaultSkills);
        _upgradeOnly = upgradeOnly;
        _totalPoints = totalPoints;
        _spentPoints = 0;

        PopulateSkills();
        UpdatePoints();
    }

    private void PopulateSkills()
    {
        SkillsList.DisposeAllChildren();
        _rowCount = 0;

        foreach (var skillId in _skillsSystem.GetAllSkillPrototypes())
        {
            var costs = _skillsSystem.GetSkillCost(skillId);
            var color = _skillsSystem.GetSkillColor(skillId);

            var defaultLevel = _defaultSkills.GetValueOrDefault(skillId, 1);
            var currentLevel = _currentSkills.GetValueOrDefault(skillId, defaultLevel);

            var skillSelector = new SkillSelector(skillId, currentLevel, costs, color, defaultLevel, _upgradeOnly)
            {
                IsLocked = _upgradeOnly && defaultLevel == 4,
            };

            skillSelector.OnSkillLevelChanged += (newLevel) =>
            {
                if (newLevel < defaultLevel)
                {
                    skillSelector.SetLevel(currentLevel);
                    return;
                }

                _currentSkills[skillId] = newLevel;
                OnSkillChanged?.Invoke(_jobId, skillId, newLevel);
                UpdatePoints();
            };

            var rowContainer = CreateSkillRow(skillSelector);
            SkillsList.AddChild(rowContainer);

            _rowCount++;
        }
    }

    private PanelContainer CreateSkillRow(SkillSelector skillSelector)
    {
        var currentRowColor = (_rowCount % 2 == 0) ? _rowColor1 : _rowColor2;

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = currentRowColor,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
            },
            Children = { skillSelector },
        };
    }

    private void UpdatePoints()
    {
        _spentPoints = CalculateTotalSpentPoints();
        var unspentPoints = _totalPoints - _spentPoints;

        PointsLabel.Text = $" {unspentPoints} / {_totalPoints}";

        UpdateSkillAvailability(unspentPoints);
    }

    private int CalculateTotalSpentPoints()
    {
        var totalSpent = 0;

        foreach (var (skillId, level) in _currentSkills)
        {
            var costs = _skillsSystem.GetSkillCost(skillId);
            var defaultLevel = _defaultSkills.GetValueOrDefault(skillId, 1);

            for (var currentLevel = defaultLevel; currentLevel < level; currentLevel++)
            {
                if (currentLevel < costs.Length)
                    totalSpent += costs[currentLevel];
            }
        }

        return totalSpent;
    }

    private void UpdateSkillAvailability(int unspentPoints)
    {
        foreach (var child in SkillsList.Children)
        {
            if (child is not PanelContainer { ChildCount: > 0 } panel)
                continue;

            if (panel.Children.ElementAt(0) is SkillSelector selector)
                selector.UpdateAvailability(unspentPoints, _skillsSystem);
        }
    }
}
