using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Orion.Notes;

//
// License-Identifier: GPL-3.0-or-later
//

[GenerateTypedNameReferences]
public sealed partial class NotesTextWindow : FancyWindow
{
    public NotesTextWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var loc = IoCManager.Resolve<ILocalizationManager>();

        CNotesTextInput.Placeholder = new Rope.Leaf(loc.GetString("notes-text-placeholder"));
        NotesTextCloseButton.OnPressed += OnClose;
    }

    public void SetNotesText(string text)
    {
        CNotesTextInput.TextRope = new Rope.Leaf(text);
    }

    private new void OnClose(BaseButton.ButtonEventArgs obj)
    {
        Close();
    }
}
