- type: entity
  parent: ProtolatheMachineCircuitboard
  id: ProtolatheAncientMachineCircuitboard
  components:
  - type: MachineBoard
    prototype: ProtolatheAncient

- type: entity
  parent: CircuitImprinterMachineCircuitboard
  id: CircuitImprinterAncientMachineCircuitboard
  components:
  - type: MachineBoard
    prototype: CircuitImprinterAncient

- type: entity
  parent: ChemDispenserMachineCircuitboard
  id: EnergyChemDispenserMachineCircuitboard
  name: energy chem dispenser machine board
  description: A machine printed circuit board for an energy chem dispenser.
  components:
  - type: MachineBoard
    prototype: EnergyChemDispenser
